version: '3'

services:
  api:
    command: sh -c "npm run build && npm run start"
    expose:
      - 4000
    restart: always
    environment:
      - NODE_ENV=prod

  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
