version: '3'
services:
  api:
    command: npm run start:watch
    stdin_open: true
    volumes:
      - ./src:/app/src
    ports:
      - 127.0.0.1:${API_PORT}:4001
    environment:
      - NODE_ENV=dev
